/**
 * Token types used throughout the normalization pipeline.
 * Structural tokens are preserved exactly; identifiers and literals
 * are normalized to canonical forms to defeat trivial renaming attacks.
 */

export const TokenTypes = {
  // Normalized identifiers / literals
  VAR: 'VAR',
  NUM: 'NUM',
  STR: 'STR',
  FUNC: 'FUNC',
  TYPE: 'TYPE',

  // Structural keywords (preserved as-is across languages)
  IF: 'IF',
  ELSE: 'ELSE',
  ELIF: 'ELIF',
  FOR: 'FOR',
  WHILE: 'WHILE',
  DO: 'DO',
  RETURN: 'RETURN',
  DEF: 'DEF',
  CLASS: 'CLASS',
  STRUCT: 'STRUCT',
  TYPEDEF: 'TYPEDEF',
  NAMESPACE: 'NAMESPACE',
  USING: 'USING',
  IMPORT: 'IMPORT',
  INCLUDE: 'INCLUDE',
  FROM: 'FROM',
  TRY: 'TRY',
  EXCEPT: 'EXCEPT',
  CATCH: 'CATCH',
  FINALLY: 'FINALLY',
  THROW: 'THROW',
  RAISE: 'RAISE',
  WITH: 'WITH',
  AS: 'AS',
  IN: 'IN',
  NOT: 'NOT',
  AND: 'AND',
  OR: 'OR',
  TRUE: 'TRUE',
  FALSE: 'FALSE',
  NONE: 'NONE',
  NULL: 'NULL',
  BREAK: 'BREAK',
  CONTINUE: 'CONTINUE',
  PASS: 'PASS',
  LAMBDA: 'LAMBDA',
  YIELD: 'YIELD',
  GLOBAL: 'GLOBAL',

  // Access modifiers & qualifiers
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  PROTECTED: 'PROTECTED',
  STATIC: 'STATIC',
  FINAL: 'FINAL',
  CONST: 'CONST',
  LET: 'LET',
  VAR_KW: 'VAR_KW',
  FUNCTION: 'FUNCTION',
  SWITCH: 'SWITCH',
  CASE: 'CASE',
  DEFAULT: 'DEFAULT',
  NEW: 'NEW',
  THIS: 'THIS',
  SUPER: 'SUPER',
  TYPEOF: 'TYPEOF',
  INSTANCEOF: 'INSTANCEOF',
  ASYNC: 'ASYNC',
  AWAIT: 'AWAIT',
  UNDEFINED: 'UNDEFINED',
  VOID: 'VOID',

  // Operators and punctuation
  ASSIGN: '=',
  PLUS: '+',
  MINUS: '-',
  MULT: '*',
  DIV: '/',
  MOD: '%',
  POWER: '**',
  EQ: '==',
  NEQ: '!=',
  SEQ: '===',
  SNEQ: '!==',
  LT: '<',
  GT: '>',
  LTE: '<=',
  GTE: '>=',
  PLUS_ASSIGN: '+=',
  MINUS_ASSIGN: '-=',
  MULT_ASSIGN: '*=',
  DIV_ASSIGN: '/=',
  MOD_ASSIGN: '%=',
  INC: '++',
  DEC: '--',
  ARROW: '=>',
  SCOPE: '::',
  DOT: '.',
  COMMA: ',',
  COLON: ':',
  SEMICOLON: ';',
  LPAREN: '(',
  RPAREN: ')',
  LBRACKET: '[',
  RBRACKET: ']',
  LBRACE: '{',
  RBRACE: '}',
  LOGICAL_AND: '&&',
  LOGICAL_OR: '||',
  BITWISE_AND: '&',
  BITWISE_OR: '|',
  BITWISE_XOR: '^',
  NOT_OP: '!',
  SPREAD: '...',
  QUESTION: '?',
};
